# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-13 04:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=160)),
                ('username', models.CharField(max_length=20)),
                ('timeline', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=160)),
                ('username', models.CharField(max_length=20)),
                ('timeline', models.CharField(max_length=20)),
                ('comment', models.ManyToManyField(to='socialnetwork.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('bio', models.CharField(blank=True, max_length=430, null=True)),
                ('avater', models.ImageField(blank=True, null=True, upload_to=b'avaterImg')),
                ('follow', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileUsername', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
